### ISSUE TITLE
In 1.0.3, the copy feature gives an error

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#463]
Hi there!

We are still using the 1.0.3 version and started noting this issue with copying an entity. When pressing 'copy' on a doc, the side panel shows an error. The console has several errors but I thought the notable one was:

```
EntityForm.tsx:168 Uncaught Error: Form has not been initialised with the correct parameters
    at EntityForm.tsx:168:19
    at mountMemo (react-dom.development.js:17225:19)
    at Object.useMemo (react-dom.development.js:17670:16)
    at useMemo (react.development.js:1650:21)
    at mc (EntityForm.tsx:160:60)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
```

Also tried with 1.0.5 but 1.0.5 is just a blank screen so still using 1.0.3.

**Comment by fgatti675** [comment]
Sorry we are not planning of fixing bugs in the previous version, I encourage you to swtich to v2 at this point!
